# Generated by Django 4.2.4 on 2023-08-29 13:26

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(
                    choices=[('Main dishes', 'Main dishes'), ('Appetizers', 'Appetizers'), ('Soups', 'Soups'),
                             ('Salads', 'Salads'), ('Steaks', 'Steaks'), ('Desserts ', 'Desserts'),
                             ('Beverages', 'Beverages')], default='Main dishes', verbose_name='Разделы кухни')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(validators=[menu.models.Validator.validatorTitleIsCapitalize],
                                  verbose_name='Название блюда')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.section')),
            ],
        ),
    ]
