# Generated by Django 3.2.20 on 2023-09-15 12:59

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0002_auto_20230915_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=50, unique=True,
                                   validators=[menu.models.Validator.validatorStringIsCapitalize],
                                   verbose_name='Название блюда'),
        ),
    ]
