# Generated by Django 4.2.4 on 2023-08-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_section_options_remove_section_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='section',
            name='section',
            field=models.CharField(choices=[('Main dishes', 'Main dishes'), ('Appetizers', 'Appetizers'), ('Soups', 'Soups'), ('Salads', 'Salads'), ('Steaks', 'Steaks'), ('Desserts ', 'Desserts'), ('Beverages', 'Beverages')], default='Main dishes', verbose_name='Разделы кухни'),
        ),
        migrations.AlterModelTable(
            name='section',
            table='Section',
        ),
    ]
