# Generated by Django 4.2.4 on 2023-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_section_options_section_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='https://nakedchef-fmr.ru/images/logo.png', upload_to='media/<django.db.models.fields.CharField>', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='the_dish',
            field=models.TextField(null=True, verbose_name='Состав блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Вес'),
        ),
    ]
