# Generated by Django 4.2.4 on 2023-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_img_menu_price_menu_the_dish_menu_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='https://nakedchef-fmr.ru/images/logo.png', height_field=800, upload_to='media/<django.db.models.fields.CharField>', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена'),
        ),
    ]
