# Generated by Django 4.2.4 on 2023-08-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_img_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='https://nakedchef-fmr.ru/images/logo.png', upload_to='media/<django.db.models.fields.CharField>', verbose_name='Картинка'),
        ),
    ]
