# Generated by Django 3.2.20 on 2023-09-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20230916_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='dish',
            new_name='menu',
        ),
    ]
