# Generated by Django 4.2.4 on 2023-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='the_dish',
            field=models.TextField(blank=True, null=True, verbose_name='Состав блюда'),
        ),
    ]
