# Generated by Django 4.2.5 on 2023-09-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
    ]
