# Generated by Django 4.2.4 on 2023-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menu_the_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='https://nakedchef-fmr.ru/images/logo.png', upload_to='menu_images/', verbose_name='Картинка'),
        ),
    ]
