# Generated by Django 4.2.4 on 2023-09-01 15:23

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_section_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(help_text='Choose: Main  dishes, Appetizers, Soups, Salads, Steaks, Desserts or Beverages', max_length=30, unique=True, validators=[menu.models.Validator.validatorCheckUniquenessTheSection], verbose_name='Разделы кухни'),
        ),
    ]
