# Generated by Django 4.2.4 on 2023-09-01 17:02

import django.core.validators
from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_menu_title_alter_section_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prices in RUB', max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(unique=True, validators=[menu.models.Validator.validatorTitleIsCapitalize, django.core.validators.MinLengthValidator(2, message='Min length must be more than 2 letters'), django.core.validators.MaxLengthValidator(30, message='Too much... Give a title shorter')], verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=100, help_text='Mention in grammes', verbose_name='Вес'),
        ),
    ]
