# Generated by Django 4.2.4 on 2023-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_menu_price_alter_menu_title_alter_menu_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.URLField(default='https://nakedchef-fmr.ru/images/logo.png', verbose_name='Картинка'),
        ),
    ]
