version: "3.9"

services:
  webapp:
    restart: always
    container_name: webapp
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000 && celery -A main.celery:app worker -l INFO && celery -A main.celery:app flower -l INFO
    depends_on:
      - db
    networks:
      - db_net
    env_file:
      - ./.env

  redis:
    image: redis
    restart: always
    ports:
      - "6377:6379"
    networks:
      - db_net

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - db_net

volumes:
  postgres_data:

networks:
  db_net:
