# Generated by Django 4.2.4 on 2023-09-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(choices=[('Зал 1', 'Зал 1'), ('Зал 2', 'Зал 2'), ('VIP lounge', 'VIP lounge'), ('Тераса', 'Тераса')], default='Зал 1', unique=True, verbose_name='Hall')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
                'db_table': 'Hall',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3')], default='A1', verbose_name='ID стола')),
                ('hall_id', models.ForeignKey(default='Зал 1', on_delete=django.db.models.deletion.CASCADE, to='orders.hall')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'Table',
            },
        ),
    ]
