# Generated by Django 3.2.20 on 2023-09-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Заказано', 'Заказано'), ('Готовится', 'Готовится'), ('Блюда в зале', 'Блюда в зале')], default='Заказано', max_length=100),
        ),
    ]
