# Generated by Django 3.2.20 on 2023-09-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall',
            field=models.CharField(choices=[('Зал 1', 'Зал 1'), ('Зал 2', 'Зал 2'), ('VIP lounge', 'VIP lounge'), ('Тераса', 'Тераса')], default='Зал 1', max_length=20, unique=True, verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='table',
            name='place',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3')], default='A1', max_length=20, verbose_name='ID стола'),
        ),
    ]
