# Generated by Django 3.2.20 on 2023-09-24 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket_history',
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=256, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2, message='The first name should contains min 2 letters')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4, 'The last name should contains min 4 letters')], verbose_name='Фамилия'),
        ),
    ]
