# Generated by Django 4.2.5 on 2023-09-08 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230908_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(default=1)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ожидается оплата', 'Ожидается оплата'), ('Оплачено', 'Оплачено'), ('Готовится', 'Готовится'), ('Блюда в зале', 'Блюда в зале')], default='<django.db.models.fields.related.ForeignKey>', max_length=100)),
                ('total_payment', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customer')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Order',
                'ordering': ['-date_ordered'],
            },
        ),
    ]
