# Generated by Django 3.2.20 on 2023-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0007_rename_dish_basket_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
